sudo: require
services: 
 - docker

before_install:
 - docker build -t dawidmbury/react-test -f ./client/Dockerfile.dev ./client #watch into client directory to see files

script:
 - docker run -e CI=true dawidmbury/react-test npm run test -- --watchAll=false

after_success: 
 - docker build -t dawidmbury/multi-client ./client
 - docker build -t dawidmbury/multi-nginx ./nginx
 - docker build -t dawidmbury/multi-server ./server
 - docker build -t dawidmbury/multi-worker ./worker
 #log in to docker-cli
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 #take these image and push to docker hub
 - docker push dawidmbury/multi-client
 - docker push dawidmbury/multi-nginx 
 - docker push dawidmbury/multi-server
 - docker push dawidmbury/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-137670674866"
 bucket_path: "docker-multi"
 on:
  branch: master
 access_key_id: 
  secure: "$AWS_ACCESS_KEY"
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
  